import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Prio Pambudi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("", fontSans.variable)}>
        <ThemeProvider>
          <Navbar />
          <main className="font-sans antialiased py-10 sm:py-16 px-6 max-w-2xl mx-auto flex flex-col min-h-[100dvh] space-y-10">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
